### ISSUE TITLE
Migrate to v0.14 branch

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna-start#11]

**Comment by mpourismaiel** [comment]
Should I use v0.14 branch or v0.14.0 tag?

**Comment by stp-ip** [comment]
I think we were agreeing on v0.14 being the better solution.

**Comment by stp-ip** [comment]
Or is there a reason not to use the branch? Not having the branch was previously blocking in your eyes on txtdirect and okkur PRs I think.

**Comment by mpourismaiel** [comment]
The branch is a much better way to go but right now branch is not in sync with the tag. Is that okay?

**Comment by stp-ip** [comment]
Only doc changes for the branch. Therefore the v0.14 branch is more up to date, but doesn't warrant a new release such as v0.14.1.

**Comment by stp-ip** [comment]
This will likely be the case that the branch is more up to date with bugfixes etc. than the specific tags. Tags are done if it warrants a new release. So probably better to stay on a branch.
