### ISSUE TITLE
`git clone` doesn't work as described in readme

### ISSUE THREAD

**Issue by gershomtripp** [okkur/syna-start#14]
`git clone git@github.com:okkur/syna-start.git project-name && cd project-name` returned an error:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

But `git clone https://github.com/okkur/syna-start project-name && cd project-name` seems to work fine.

**Comment by stp-ip** [comment]
Thanks happy to accept a PR or fix it in the coming days ourselves.

Great catch. Due to the team probably working with ssh based git more than https, but definitely should be using https.

**Comment by stp-ip** [comment]
We now switched to vanity urls so that we have better insights as well as won't need to break the url in the long run: `git clone https://git.okkur.org/syna-start`
