### ISSUE TITLE
Git submodule URL for Syna is wrong 

### ISSUE THREAD

**Issue by joelsherrill** [okkur/syna-start#26]
Line 3 of .gitmodules references https://git.okkur.org/syna when it should reference https://github.com/okkur/syna

It is also wrong in README.md.

**Comment by stp-ip** [comment]
This should be correct. "https://git.okkur.org/syna" is a valid redirect, which can be used to migrated the repo later without breaking people.

Did you get any specific errors or had any issues with that link being used?
