### ISSUE TITLE
bug in head.html

### ISSUE THREAD

**Issue by momargoh** [okkur/syna-start#42]
Hi there. I'm having trouble building the site (Ubuntu 20.04, Hugo extended v0.68.3) due to a bug in head.html

**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
```
Building sites … ERROR 2020/09/13 22:31:43 render of "home" failed: execute of template failed: template: _default/list.html:6:6: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/home/momar/Documents/websites/syna-start/themes/syna/layouts/partials/head.html:55:124": execute of template failed: template: partials/head.html:55:124: executing "partials/head.html" at <resources>: can't evaluate field PostProcess in type interface {}

```

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone --recurse-submodules https://git.okkur.org/syna-start
npm install -g postcss-cli
hugo
```

**Environment**:
- Hugo version:  v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

**Comment by stp-ip** [comment]
PostProcess from Hugo is only supported in Hugo with versions v0.69+. This should work with any version above v0.69+ and postcss-cli installed (as you already seem to have).

Let us know, if that resolves the issue.

**Comment by stp-ip** [comment]
Postcss-cli should not be mandatory with v0.17.4
