### ISSUE TITLE
SSL certificate problem: certificate has expired, can't clone 

### ISSUE THREAD

**Issue by chepo92** [okkur/syna-start#46]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
`git clone --recurse-submodules https://git.okkur.org/syna-start`

```
Cloning into `syna-start`...
fatal: unable to access 'https://git.okkur.org/syna-start/': SSL certificate problem: certificate has expired
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Syna Theme Starter version:  
- Hugo version:  
- Others:

**Comment by stp-ip** [comment]
Fixed. We use a Caddy based backend for this and it ran into a weird issue. We'll investigate.
